[package]
name = "rp-pico-w"
version = "0.0.1"
authors = ["The rp-rs Developers"]
edition = "2018"
homepage = "https://github.com/rp-rs/rp-hal/tree/main/boards/rp-pico-w"
description = "Board Support Package for the Raspberry Pi Pico W"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rp-rs/rp-hal.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m = "0.7.2"
rp2040-boot2 = { version = "0.2.0", optional = true }
rp2040-hal = { path = "../../rp2040-hal", version = "0.6.0", features=["eh1_0_alpha"] }
cortex-m-rt = { version = "0.7", optional = true }
embassy-time = { version = "0.1.0", features = ["tick-hz-1_000_000"] }
embassy-sync = { version = "0.1.0" }

defmt = "0.3"

atomic-polyfill = "0.1.8"
critical-section = "1.1.0"
embedded-hal = "0.2.7"
embedded-hal-1 = { version = "=1.0.0-alpha.9", package = "embedded-hal" }
fugit = "0.3.6"

[dev-dependencies]
panic-probe = { version = "0.3", features = ["print-defmt"] }
cyw43 = { version = "0.1.0", git = "https://github.com/jannic-dev-forks/cyw43", branch = "stable", features=["defmt"] }
embassy-executor = { version = "0.1.1", features=["integrated-timers"] }
embassy-futures = { version = "0.1.0" }
embassy-net = { version = "0.1.0", git = "https://github.com/embassy-rs/embassy.git", rev = "2528f451387e6c7b27c3140cd87d47521d1971a2",  features = ["defmt", "tcp", "dhcpv4", "medium-ethernet", "pool-16"] }
defmt-rtt = "0.3"
embedded-hal-bus = "0.1.0-alpha.1"

[features]
default = ["boot2", "rt", "critical-section-impl"]
critical-section-impl = ["rp2040-hal/critical-section-impl"]
boot2 = ["rp2040-boot2"]
rt = ["cortex-m-rt","rp2040-hal/rt"]
fix_fw = ["cyw43/fix_fw"]
